### ISSUE TITLE
Support for swift version 4.1

### ISSUE THREAD

**Issue by manoomanish** [Kumulos/KumulosSdkSwift#35]
How can i pod install to support swift version 4.1/Xcode 9.4.1 environment ?

**Comment by cgwyllie** [comment]
Hi @manoomanish,

Swift 4.1 is not a target that we support, the closest is Swift 4.2 from SDK versions 3.x and 4.x.

We would recommend updating to a later Xcode version and migrating your project to a newer Swift version if possible. By April 2020 all App Store builds should be compiled with Xcode 11 and the iOS 13 toolchain.

If you would like further assistance with this, please contact our support team via support@kumulos.com.
