### ISSUE TITLE
Compile time error: KSPushNotification

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [Kumulos/KumulosSdkSwift#37]
Hi Team,

Firstly, Thank you for this wonderful SDK.
I am integrating **KumulosSdkSwift** into my project.
I am facing compile time error during configuring `PushTrackOpen` function.
I am attaching screenshot for the same error.
Please guide us on how to overcome this error.

![Screenshot 2019-10-15 at 5 01 24 PM](https://user-images.githubusercontent.com/19154948/66828144-f016a380-ef6d-11e9-82f6-6916e52e5f14.png)

Thank you,
Rashesh

**Comment by cgwyllie** [comment]
Hi Rashesh,

It looks like you may be upgrading from an older version of the SDK.

The newer versions of the SDK automatically handle token registration, and open tracking for you. As part of the update, you should remove any existing notification center delegate code and move any custom logic into the provided handler blocks.

Please review the updated Messaging documentation for further details: https://docs.kumulos.com/integration/swift/#messaging-push-notifications

If you have any more specific questions, please feel free to contact support@kumulos.com and we'll assist further.

Kind regards,
  Chris

P.S. if you do feel this is an error with the SDK, please reopen the issue.
